/**
 * Bootstrap script for the SQLite local database.
 * Creates the DB file and applies all migrations generated by drizzle-kit.
 *
 * Generate migrations first:
 *   pnpm --filter @workspace/db run generate:sqlite
 *
 * Then run this script to apply them:
 *   SQLITE_PATH=./farmasystem.db pnpm --filter @workspace/db run migrate:sqlite
 *
 * Or use the quicker push (dev only):
 *   SQLITE_PATH=file:./farmasystem.db pnpm --filter @workspace/db run push:sqlite
 */

import { createClient } from "@libsql/client";
import { drizzle } from "drizzle-orm/libsql";
import { migrate } from "drizzle-orm/libsql/migrator";
import path from "path";
import os from "os";
import { mkdirSync } from "fs";

const rawPath =
  process.env["SQLITE_PATH"] ??
  path.join(os.homedir(), ".farmasystem", "farmasystem.db");

const resolvedPath = rawPath.startsWith("file:") ? rawPath.slice(5) : rawPath;
const dbDir = path.dirname(resolvedPath);
mkdirSync(dbDir, { recursive: true });

const url = rawPath.startsWith("file:") ? rawPath : `file:${rawPath}`;

const client = createClient({ url });
const db = drizzle(client);

const migrationsFolder = path.join(
  path.dirname(new URL(import.meta.url).pathname),
  "..",
  "drizzle",
  "sqlite",
);

console.log(`[migrate-sqlite] Using database: ${url}`);
console.log(`[migrate-sqlite] Migrations folder: ${migrationsFolder}`);

await migrate(db, { migrationsFolder });

console.log("[migrate-sqlite] Migrations complete.");
await client.close();
